name: Unit Tests

on:
  workflow_dispatch: {}
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 16

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd ${{ github.workspace }}
        bash scripts/run_unit_tests.sh
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: Unit Tests            
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit 

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
